name: ipot
description: "Customer QR ordering app."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^14.6.0
  dio: ^5.7.0
  mobile_scanner: ^6.0.0
  cached_network_image: ^3.4.1
  flutter_dotenv: ^5.2.1
  intl: ^0.20.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
